<a href="https://colab.research.google.com/github/Otto-C/Predict_Data/blob/master/Working_Reg_Predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression Predict Student Solution

© Explore Data Science Academy

---
### Honour Code

I {**YOUR NAME, YOUR SURNAME**}, confirm - by submitting this document - that the solutions in this notebook are a result of my own work and that I abide by the [EDSA honour code](https://drive.google.com/file/d/1QDCjGZJ8-FmJE3bZdIQNwnJyQKPhHZBn/view?usp=sharing).

Non-compliance with the honour code constitutes a material breach of contract.

### Predict Overview: Spain Electricity Shortfall Challenge

The government of Spain is considering an expansion of it's renewable energy resource infrastructure investments. As such, they require information on the trends and patterns of the countries renewable sources and fossil fuel energy generation. Your company has been awarded the contract to:

- 1. analyse the supplied data;
- 2. identify potential errors in the data and clean the existing data set;
- 3. determine if additional features can be added to enrich the data set;
- 4. build a model that is capable of forecasting the three hourly demand shortfalls;
- 5. evaluate the accuracy of the best machine learning model;
- 6. determine what features were most important in the model’s prediction decision, and
- 7. explain the inner working of the model to a non-technical audience.

Formally the problem statement was given to you, the senior data scientist, by your manager via email reads as follow:

> In this project you are tasked to model the shortfall between the energy generated by means of fossil fuels and various renewable sources - for the country of Spain. The daily shortfall, which will be referred to as the target variable, will be modelled as a function of various city-specific weather features such as `pressure`, `wind speed`, `humidity`, etc. As with all data science projects, the provided features are rarely adequate predictors of the target variable. As such, you are required to perform feature engineering to ensure that you will be able to accurately model Spain's three hourly shortfalls.
 
On top of this, she has provided you with a starter notebook containing vague explanations of what the main outcomes are.

<a id="cont"></a>

## Table of Contents

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Loading Data</a>

<a href=#three>3. Exploratory Data Analysis (EDA)</a>

<a href=#four>4. Data Engineering</a>

<a href=#five>5. Modeling</a>

<a href=#six>6. Model Performance</a>

<a href=#seven>7. Model Explanations</a>

 <a id="one"></a>
## 1. Importing Packages
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Importing Packages ⚡ |
| :--------------------------- |
| In this section you are required to import, and briefly discuss, the libraries that will be used throughout your analysis and modelling. |

---

In [1]:
# Libraries for data loading, data manipulation and data visulisation
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
import warnings

# Libraries for data preparation and model building
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics

# Setting global constants to ensure notebook results are reproducible
#PARAMETER_CONSTANT = ###

<a id="two"></a>
## 2. Loading the Data
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Loading the data ⚡ |
| :--------------------------- |
| In this section you are required to load the data from the `df_train` file into a DataFrame. |

---

In [3]:
df_Git = pd.read_csv('https://raw.githubusercontent.com/Otto-C/Predict_Data/master/df_train.csv')
df_Git.head()
df = df_Git.copy()
del df['Unnamed: 0']

                  time  Madrid_wind_speed  ... Madrid_temp_min  load_shortfall_3h
0  2015-01-01 03:00:00           0.666667  ...      265.938000        6715.666667
1  2015-01-01 06:00:00           0.333333  ...      266.386667        4171.666667
2  2015-01-01 09:00:00           1.000000  ...      272.708667        4274.666667
3  2015-01-01 12:00:00           1.000000  ...      281.895219        5075.666667
4  2015-01-01 15:00:00           1.000000  ...      280.678437        6620.666667

[5 rows x 48 columns]

<a id="three"></a>
## 3. Exploratory Data Analysis (EDA)
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Exploratory data analysis ⚡ |
| :--------------------------- |
| In this section, you are required to perform an in-depth analysis of all the variables in the DataFrame. |

---

In [4]:
# look at data statistics
df.head()

                  time  Madrid_wind_speed  ... Madrid_temp_min  load_shortfall_3h
0  2015-01-01 03:00:00           0.666667  ...      265.938000        6715.666667
1  2015-01-01 06:00:00           0.333333  ...      266.386667        4171.666667
2  2015-01-01 09:00:00           1.000000  ...      272.708667        4274.666667
3  2015-01-01 12:00:00           1.000000  ...      281.895219        5075.666667
4  2015-01-01 15:00:00           1.000000  ...      280.678437        6620.666667

[5 rows x 48 columns]

In [5]:
# look at data statistics
df.shape

(8763, 48)

In [6]:
# look at data statistics
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 48 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  8763 non-null   object
 1   Madrid_wind_speed     8763 non-null   float64
 2   Valencia_wind_deg     8763 non-null   object
 3   Bilbao_rain_1h        8763 non-null   float64
 4   Valencia_wind_speed   8763 non-null   float64
 5   Seville_humidity      8763 non-null   float64
 6   Madrid_humidity       8763 non-null   float64
 7   Bilbao_clouds_all     8763 non-null   float64
 8   Bilbao_wind_speed     8763 non-null   float64
 9   Seville_clouds_all    8763 non-null   float64
 10  Bilbao_wind_deg       8763 non-null   float64
 11  Barcelona_wind_speed  8763 non-null   float64
 12  Barcelona_wind_deg    8763 non-null   float64
 13  Madrid_clouds_all     8763 non-null   float64
 14  Seville_wind_speed    8763 non-null   float64
 15  Barcelona_rain_1h     8763 non-null   float64
 16  Seville_pressure      8763 non-null   object
 17  Seville_rain_1h       8763 non-null   float64
 18  Bilbao_snow_3h        8763 non-null   float64
 19  Barcelona_pressure    8763 non-null   float64
 20  Seville_rain_3h       8763 non-null   float64
 21  Madrid_rain_1h        8763 non-null   float64
 22  Barcelona_rain_3h     8763 non-null   float64
 23  Valencia_snow_3h      8763 non-null   float64
 24  Madrid_weather_id     8763 non-null   float64
 25  Barcelona_weather_id  8763 non-null   float64
 26  Bilbao_pressure       8763 non-null   float64
 27  Seville_weather_id    8763 non-null   float64
 28  Valencia_pressure     6695 non-null   float64
 29  Seville_temp_max      8763 non-null   float64
 30  Madrid_pressure       8763 non-null   float64
 31  Valencia_temp_max     8763 non-null   float64
 32  Valencia_temp         8763 non-null   float64
 33  Bilbao_weather_id     8763 non-null   float64
 34  Seville_temp          8763 non-null   float64
 35  Valencia_humidity     8763 non-null   float64
 36  Valencia_temp_min     8763 non-null   float64
 37  Barcelona_temp_max    8763 non-null   float64
 38  Madrid_temp_max       8763 non-null   float64
 39  Barcelona_temp        8763 non-null   float64
 40  Bilbao_temp_min       8763 non-null   float64
 41  Bilbao_temp           8763 non-null   float64
 42  Barcelona_temp_min    8763 non-null   float64
 43  Bilbao_temp_max       8763 non-null   float64
 44  Seville_temp_min      8763 non-null   float64
 45  Madrid_temp           8763 non-null   float64
 46  Madrid_temp_min       8763 non-null   float64
 47  load_shortfall_3h     8763 non-null   float64
dtypes: float64(45), object(3)
memory usage: 3.2+ MB

In [7]:
# look at data statistics
df.describe()

       Madrid_wind_speed  Bilbao_rain_1h  ...  Madrid_temp_min  load_shortfall_3h
count        8763.000000     8763.000000  ...      8763.000000        8763.000000
mean            2.425729        0.135753  ...       287.202203       10673.857612
std             1.850371        0.374901  ...         9.206237        5218.046404
min             0.000000        0.000000  ...       264.983333       -6618.000000
25%             1.000000        0.000000  ...       280.299167        7390.333333
50%             2.000000        0.000000  ...       286.083333       11114.666667
75%             3.333333        0.100000  ...       293.884500       14498.166667
max            13.000000        3.000000  ...       310.383333       31904.000000

[8 rows x 45 columns]

In [8]:
# Inspecting Null values for each column
df.isnull().sum()

time                       0
Madrid_wind_speed          0
Valencia_wind_deg          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_pressure           0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2068
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
load_shortfall_3h          0
dtype: int64

In [9]:
# Checking Skew
df.skew()

Madrid_wind_speed        1.441144
Bilbao_rain_1h           5.222802
Valencia_wind_speed      3.499637
Seville_humidity        -0.310175
Madrid_humidity         -0.057378
Bilbao_clouds_all       -0.053085
Bilbao_wind_speed        1.716914
Seville_clouds_all       1.814452
Bilbao_wind_deg          0.226927
Barcelona_wind_speed     1.057331
Barcelona_wind_deg      -0.180001
Madrid_clouds_all        1.246745
Seville_wind_speed       1.151006
Barcelona_rain_1h        8.726988
Seville_rain_1h          8.067341
Bilbao_snow_3h          26.177568
Barcelona_pressure      57.979664
Seville_rain_3h         19.342574
Madrid_rain_1h           7.074308
Barcelona_rain_3h       12.696605
Valencia_snow_3h        63.298084
Madrid_weather_id       -3.107722
Barcelona_weather_id    -2.584011
Bilbao_pressure         -0.999642
Seville_weather_id      -3.275574
Valencia_pressure       -1.705162
Seville_temp_max        -0.033931
Madrid_pressure         -1.850768
Valencia_temp_max        0.082672
Valencia_temp            0.057476
Bilbao_weather_id       -1.234844
Seville_temp             0.157238
Valencia_humidity       -0.305757
Valencia_temp_min        0.081832
Barcelona_temp_max       0.276925
Madrid_temp_max          0.298707
Barcelona_temp           0.128095
Bilbao_temp_min          0.194912
Bilbao_temp              0.293686
Barcelona_temp_min      -0.018057
Bilbao_temp_max          0.393932
Seville_temp_min         0.265482
Madrid_temp              0.304123
Madrid_temp_min          0.275083
load_shortfall_3h       -0.384847
dtype: float64

In [10]:
#Checking Kurtosis
df.kurtosis()

Madrid_wind_speed          2.036462
Bilbao_rain_1h            32.904656
Valencia_wind_speed       35.645426
Seville_humidity          -1.017983
Madrid_humidity           -1.167537
Bilbao_clouds_all         -1.533417
Bilbao_wind_speed          3.631565
Seville_clouds_all         2.155921
Bilbao_wind_deg           -1.083530
Barcelona_wind_speed       1.493635
Barcelona_wind_deg        -0.959160
Madrid_clouds_all          0.142079
Seville_wind_speed         1.398580
Barcelona_rain_1h        101.578931
Seville_rain_1h           93.840746
Bilbao_snow_3h           806.128471
Barcelona_pressure      3687.564230
Seville_rain_3h          413.136592
Madrid_rain_1h            76.584491
Barcelona_rain_3h        187.800460
Valencia_snow_3h        4089.323165
Madrid_weather_id          9.259047
Barcelona_weather_id       5.701882
Bilbao_pressure            1.825323
Seville_weather_id        10.710308
Valencia_pressure          2.211823
Seville_temp_max          -0.515989
Madrid_pressure            2.216199
Valencia_temp_max         -0.613755
Valencia_temp             -0.643793
Bilbao_weather_id          0.067814
Seville_temp              -0.504132
Valencia_humidity         -0.734345
Valencia_temp_min         -0.599551
Barcelona_temp_max        -0.728757
Madrid_temp_max           -0.662861
Barcelona_temp            -0.696555
Bilbao_temp_min           -0.230342
Bilbao_temp               -0.086363
Barcelona_temp_min        -0.474890
Bilbao_temp_max            0.283366
Seville_temp_min          -0.475564
Madrid_temp               -0.612299
Madrid_temp_min           -0.666646
load_shortfall_3h         -0.118999
dtype: float64

In [ ]:
# plot relevant feature interactions

In [ ]:
# evaluate correlation
df.corr()

                      Unnamed: 0  ...  load_shortfall_3h
Unnamed: 0              1.000000  ...           0.192612
Madrid_wind_speed      -0.109288  ...          -0.150981
Bilbao_rain_1h         -0.249633  ...          -0.152510
Valencia_wind_speed    -0.090161  ...          -0.142791
Seville_humidity       -0.079025  ...          -0.167290
Madrid_humidity        -0.103359  ...          -0.150536
Bilbao_clouds_all      -0.068123  ...          -0.127293
Bilbao_wind_speed       0.049197  ...          -0.081602
Seville_clouds_all     -0.140583  ...          -0.091804
Bilbao_wind_deg        -0.155738  ...          -0.120800
Barcelona_wind_speed   -0.218781  ...          -0.103633
Barcelona_wind_deg     -0.140449  ...          -0.116133
Madrid_clouds_all      -0.116928  ...          -0.081623
Seville_wind_speed     -0.093926  ...          -0.048433
Barcelona_rain_1h      -0.075692  ...          -0.056633
Seville_rain_1h        -0.075340  ...          -0.031572
Bilbao_snow_3h         -0.092377  ...          -0.031721
Barcelona_pressure     -0.040157  ...          -0.034385
Seville_rain_3h        -0.082525  ...          -0.032945
Madrid_rain_1h         -0.068980  ...          -0.027159
Barcelona_rain_3h      -0.104326  ...          -0.024720
Valencia_snow_3h       -0.028130  ...          -0.021633
Madrid_weather_id       0.047202  ...           0.030868
Barcelona_weather_id    0.034761  ...           0.063868
Bilbao_pressure        -0.022475  ...           0.039052
Seville_weather_id      0.072472  ...           0.061104
Valencia_pressure       0.267772  ...           0.086022
Seville_temp_max        0.039424  ...           0.109834
Madrid_pressure         0.385578  ...           0.092638
Valencia_temp_max       0.087002  ...           0.144270
Valencia_temp           0.135294  ...           0.173225
Bilbao_weather_id       0.192485  ...           0.145875
Seville_temp            0.042897  ...           0.159343
Valencia_humidity       0.023917  ...           0.043140
Valencia_temp_min       0.185468  ...           0.201863
Barcelona_temp_max      0.047417  ...           0.164734
Madrid_temp_max         0.093378  ...           0.182548
Barcelona_temp          0.068078  ...           0.182673
Bilbao_temp_min         0.028698  ...           0.172920
Bilbao_temp             0.081799  ...           0.176411
Barcelona_temp_min      0.103436  ...           0.195984
Bilbao_temp_max         0.146216  ...           0.180934
Seville_temp_min        0.037487  ...           0.174718
Madrid_temp             0.088439  ...           0.186036
Madrid_temp_min         0.085197  ...           0.174744
load_shortfall_3h       0.192612  ...           1.000000

[46 rows x 46 columns]

In [ ]:
# have a look at feature distributions

<a id="four"></a>
## 4. Data Engineering
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Data engineering ⚡ |
| :--------------------------- |
| In this section you are required to: clean the dataset, and possibly create new features - as identified in the EDA phase. |

---

In [ ]:
# remove missing values/ features

In [ ]:
# create new features

In [ ]:
# engineer existing features

<a id="five"></a>
## 5. Modelling
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Modelling ⚡ |
| :--------------------------- |
| In this section, you are required to create one or more regression models that are able to accurately predict the thee hour load shortfall. |

---

In [ ]:
# split data

In [ ]:
# create targets and features dataset

In [ ]:
# create one or more ML models

In [ ]:
# evaluate one or more ML models

<a id="six"></a>
## 6. Model Performance
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model performance ⚡ |
| :--------------------------- |
| In this section you are required to compare the relative performance of the various trained ML models on a holdout dataset and comment on what model is the best and why. |

---

In [ ]:
# Compare model performance

In [ ]:
# Choose best model and motivate why it is the best choice

<a id="seven"></a>
## 7. Model Explanations
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model explanation ⚡ |
| :--------------------------- |
| In this section, you are required to discuss how the best performing model works in a simple way so that both technical and non-technical stakeholders can grasp the intuition behind the model's inner workings. |

---

In [ ]:
# discuss chosen methods logic